"""report submitter key

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 10:23:23.864812
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reports", sa.Column("submitter_key", sa.Text(), nullable=True))
    op.create_index(
        "ix_reports_submitter_key_submitted_at",
        "reports",
        ["submitter_key", "submitted_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reports_submitter_key_submitted_at", table_name="reports")
    op.drop_column("reports", "submitter_key")
    # ### end Alembic commands ###
